//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Executor_Testes.Exec.Mod
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Qualidade : DbContext
    {
        public Qualidade()
            : base("name=Qualidade")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ordem_Execucao_Automacao> Ordem_Execucao_Automacao { get; set; }
        public virtual DbSet<TreeViewExecucaoAutomacao> TreeViewExecucaoAutomacao { get; set; }
    
        public virtual int sp_RetornaTreeViewAutomacao()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RetornaTreeViewAutomacao");
        }
    
        public virtual int sp_RetornaTreeViewAutomacaoAccount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RetornaTreeViewAutomacaoAccount");
        }
    
        public virtual int sp_RetornaTreeViewAutomacaoIkcadm()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RetornaTreeViewAutomacaoIkcadm");
        }
    
        public virtual int sp_RetornaTreeViewAutomacaoLogistics()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RetornaTreeViewAutomacaoLogistics");
        }
    
        public virtual int sp_RetornaTreeViewAutomacaoManager()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RetornaTreeViewAutomacaoManager");
        }
    
        public virtual int sp_RetornaTreeViewAutomacaoMobile()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RetornaTreeViewAutomacaoMobile");
        }
    
        public virtual int sp_RetornaTreeViewAutomacaoOther1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RetornaTreeViewAutomacaoOther1");
        }
    
        public virtual int sp_RetornaTreeViewAutomacaoOther2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RetornaTreeViewAutomacaoOther2");
        }
    
        public virtual int sp_RetornaTreeViewAutomacaoOther3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RetornaTreeViewAutomacaoOther3");
        }
    
        public virtual int sp_RetornaTreeViewAutomacaoOther4()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RetornaTreeViewAutomacaoOther4");
        }
    
        public virtual int sp_RetornaTreeViewAutomacaoOther5()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RetornaTreeViewAutomacaoOther5");
        }
    
        public virtual int sp_RetornaTreeViewAutomacaoPay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RetornaTreeViewAutomacaoPay");
        }
    }
}
