//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Executor_Testes.Exec.Mod
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordem_Execucao_Automacao
    {
        public int Codigo { get; set; }
        public int Ordem { get; set; }
        public string Tabela { get; set; }
        public string Funcionalidade { get; set; }
        public string Nome_Teste { get; set; }
        public string Tabelas_Adicionais { get; set; }
    }
}
