//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Executor_Testes.Exec.Mod
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreeViewExecucaoAutomacao
    {
        public int ID { get; set; }
        public int ID_Teste { get; set; }
        public string Tabela { get; set; }
        public int TestCaseID { get; set; }
        public string Descricao_CasoTeste { get; set; }
        public bool Executar { get; set; }
        public string Nome_Teste { get; set; }
        public string Funcionalidade { get; set; }
        public int OrdemExecucao { get; set; }
        public int ID_Suite { get; set; }
        public int ID_Config { get; set; }
        public bool MassaDados { get; set; }
        public string Tabelas_Adicionais { get; set; }
    }
}
